### ISSUE TITLE
Can't run the `bassegnet_jazz.h5` model

### ISSUE THREAD

**Issue by xavriley** [jakobabesser/bassunet#2]
It looks like the `bassegnet_jazz.h5` file should be renamed to `basssegnet_jazz.h5` (note the extra `s`) to match the code.

With this change in place, its still failing for me with the following error:

```
ValueError: Unknown layer: MaxPoolingWithArgmax2D
```

which is coming from

```
Traceback (most recent call last):
  File "bassunet.py", line 190, in <module>
    bun = BassUNet("basssegnet_jazz.h5")
  File "bassunet.py", line 34, in __init__
    self.__model = load_model(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'data', fn_model))
```

I can use the other model without issues so it looks like something to do with a custom layer. Apologies as I'm not very familiar with Keras.

**Comment by jakobabesser** [comment]
@xavriley I added the `custom_object` dictionary in the `load_model()` call in `bassunet.py` (l. 35). Please try again, whether this fixes your issue.
